name: Build iOS App

on:
  push:
    branches: [ "main" ]   # trigger bij push naar main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest   # GitHub draait dit op een Mac-omgeving

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0" # pas aan naar jouw Flutter versie
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign